import {_electron} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import sharp from 'sharp';
const root=path.resolve('.'),work=path.join(root,'.runtime-comparison-'+Date.now());await fs.mkdir(work,{recursive:true});const file=path.join(work,'low-contrast.png');const raw=Buffer.alloc(640*480*3);for(let y=0;y<480;y++)for(let x=0;x<640;x++){const i=(y*640+x)*3;raw[i]=70+x/10;raw[i+1]=90+y/8;raw[i+2]=100+(x+y)/20;}await sharp(raw,{raw:{width:640,height:480,channels:3}}).png().toFile(file);
const env={...process.env,SWITCHYARD_TEST_DATA:path.join(work,'profile')};delete env.ELECTRON_RUN_AS_NODE;const config={executablePath:process.env.SWITCHYARD_TEST_EXE||path.join(root,'node_modules/electron/dist/electron.exe'),args:[...(process.env.SWITCHYARD_TEST_EXE?[]:[root]),'--disable-backgrounding-occluded-windows','--disable-renderer-backgrounding'],env};let app=await _electron.launch(config);const results=[];
try{
 let page=await app.firstWindow();page.setDefaultTimeout(20000);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setTitle('Switchyard - comparison verification'));
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'Add files',exact:true}).first().click();await page.getByRole('button',{name:'Make something better'}).click();const start=performance.now();await page.getByRole('button',{name:'Run tool',exact:true}).click();await page.getByRole('button',{name:'Compare before & after'}).waitFor();const visibleMs=Math.round(performance.now()-start);await page.getByText('Processing time:',{exact:false}).waitFor();results.push({flow:'UI run to completed image result with measured processing duration',visibleMs});
 await page.getByRole('button',{name:'Compare before & after'}).click();await page.getByRole('slider',{name:'Reveal processed image'}).waitFor();await page.waitForFunction(()=>[...document.querySelectorAll('.comparison-stage img')].every(im=>im.complete&&im.naturalWidth>0));const slider=page.getByRole('slider');await slider.focus();await slider.press('Home');const before=await page.locator('.comparison-stage').screenshot();await slider.press('End');const after=await page.locator('.comparison-stage').screenshot();assert.notDeepEqual(before,after);results.push({flow:'Both actual previews decode and keyboard slider reveals different pixels'});await slider.press('Home');await slider.press('ArrowRight');assert.equal(await slider.inputValue(),'1');await page.getByRole('button',{name:'Hide comparison'}).click();assert.equal(await page.locator('.comparison-stage').count(),0);results.push({flow:'Slider keyboard increments and Hide comparison work'});
 await app.close();app=await _electron.launch(config);page=await app.firstWindow();await page.getByRole('button',{name:'Queue & history',exact:true}).click();await page.getByRole('button',{name:'Compare before & after'}).click();await page.getByRole('slider').waitFor();results.push({flow:'Source and result comparison survives full application restart'});await page.screenshot({path:path.join(root,'docs/verification/comparison.png')});
 await fs.rename(file,file+'.moved');await page.getByRole('button',{name:'Hide comparison'}).click();await page.getByRole('button',{name:'Compare before & after'}).click();await page.getByRole('alert').filter({hasText:'Could not load the comparison'}).waitFor();const state=await page.evaluate(()=>window.switchyard.state());await fs.access(state.jobs[0].outputs[0]);results.push({flow:'Missing original gives visible feedback and preserves saved output'});
 await fs.rename(file+'.moved',file);await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);await page.getByRole('button',{name:'Add files',exact:true}).first().click();await page.getByRole('textbox',{name:'Search tools'}).fill('Resize image');await page.locator('.tool-open').filter({has:page.getByRole('heading',{name:'Resize image',exact:true})}).click();await page.getByRole('spinbutton',{name:/Width/}).fill('80');await page.getByRole('spinbutton',{name:/Height/}).fill('60');await page.getByRole('button',{name:'Run tool'}).click();const firstJob=page.locator('.job').first();await firstJob.getByRole('button',{name:'Compare before & after'}).click();await firstJob.locator('.comparison-pair').waitFor();assert.match(await firstJob.locator('figcaption').last().innerText(),/80 × 60/);results.push({flow:'Different dimensions use paired previews with accurate output size'});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(900,650));await page.getByRole('button',{name:'Toggle theme'}).click();await firstJob.locator('.comparison-pair').scrollIntoViewIfNeeded();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');results.push({flow:'Comparison remains usable at minimum window size and in dark theme'});
 await fs.writeFile(path.join(root,'docs/verification/comparison-flows.json'),JSON.stringify({passed:results.length,results},null,2));console.log(results);
}finally{await app.close();}
