// Result contracts: decode outputs and check the promised transformation.
// File existence is deliberately not a success criterion.
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import sharp from 'sharp';
import jsQR from 'jsqr';
import {PDFDocument} from 'pdf-lib';
import {tools,defaults,toolById} from '../shared/catalog.mjs';
import {processTool,command} from '../electron/processor.mjs';
import {parseCsv} from '../electron/extras.mjs';

const root=path.resolve('.'),work=path.join(root,'.runtime-outcomes-'+Date.now());await fs.mkdir(work,{recursive:true});
const engines={ffmpeg:path.join(root,'engines/ffmpeg/ffmpeg.exe'),ffprobe:path.join(root,'engines/ffmpeg/ffprobe.exe'),ocrModels:path.join(root,'engines/ocr')};
let serial=0,app,page;
if(process.env.SWITCHYARD_TEST_EXE){
 const {_electron}=await import('playwright');const env={...process.env,SWITCHYARD_TEST_DATA:path.join(work,'profile')};delete env.ELECTRON_RUN_AS_NODE;
 app=await _electron.launch({executablePath:process.env.SWITCHYARD_TEST_EXE,env});page=await app.firstWindow();await page.getByRole('button',{name:'Switchyard home'}).waitFor();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setTitle('Switchyard - output correctness audit'));
}
async function run(id,files=[],options={},text=''){
 const request={toolId:id,files,options:{...defaults(toolById[id]),...options},text};
 if(!app)return processTool(request,{outputDir:path.join(work,String(++serial)),engines});
 await page.evaluate(files=>window.switchyard.addPaths(files),files);const jobId=await page.evaluate(request=>window.switchyard.run(request),request),end=Date.now()+180000;
 while(Date.now()<end){const job=await page.evaluate(async id=>(await window.switchyard.state()).jobs.find(j=>j.id===id),jobId);if(job&&['done','partial','error','cancelled'].includes(job.status)){assert.equal(job.status,'done',job.error||job.text);return job;}await new Promise(r=>setTimeout(r,40));}throw new Error('Timed out '+id);
}
const cases=[],results=[];function check(id,description,fn){cases.push({id,description,fn});}
const near=(a,b,tolerance=.02)=>assert.ok(Math.abs(a-b)<=tolerance,`${a} differs from ${b} (tolerance ${tolerance})`);
const pixels=async file=>sharp(file).rotate().ensureAlpha().raw().toBuffer({resolveWithObject:true});
const pixel=(im,x,y)=>[...im.data.subarray((y*im.info.width+x)*4,(y*im.info.width+x)*4+4)];
const mean=arr=>arr.reduce((a,b)=>a+b,0)/arr.length;
function difference(a,b){assert.equal(a.data.length,b.data.length);let sum=0;for(let i=0;i<a.data.length;i++)if(i%4!==3)sum+=Math.abs(a.data[i]-b.data[i]);return sum/(a.data.length*.75);}
function edge(im){let sum=0,count=0;for(let y=1;y<im.info.height;y++)for(let x=1;x<im.info.width;x++){const i=(y*im.info.width+x)*4;sum+=Math.abs(im.data[i]-im.data[i-4])+Math.abs(im.data[i]-im.data[i-im.info.width*4]);count+=2;}return sum/count;}
function range(im){const values=[];for(let i=0;i<im.data.length;i+=4)values.push((im.data[i]+im.data[i+1]+im.data[i+2])/3);values.sort((a,b)=>a-b);return values[Math.floor(values.length*.98)]-values[Math.floor(values.length*.02)];}
const W=320,H=240,raw=Buffer.alloc(W*H*3);for(let y=0;y<H;y++)for(let x=0;x<W;x++){const i=(y*W+x)*3;raw[i]=45+Math.round(x/W*110)+(Math.floor(x/12)%2)*18;raw[i+1]=65+Math.round(y/H*100);raw[i+2]=90+Math.round((x+y)/(W+H)*60);}
const image=path.join(work,'gradient.png');await sharp(raw,{raw:{width:W,height:H,channels:3}}).png().toFile(image);const source=await pixels(image);
const blurred=path.join(work,'soft.png');await sharp(image).blur(1.5).png().toFile(blurred);
const tagged=path.join(work,'tagged.jpg');await sharp(image).withMetadata({exif:{IFD0:{Artist:'OUTCOME AUDIT'}}}).jpeg().toFile(tagged);
const bordered=path.join(work,'border.png');await sharp(image).extend({top:10,bottom:10,left:10,right:10,background:'#ffffff'}).png().toFile(bordered);
const solid=path.join(work,'red.png');await sharp({create:{width:80,height:60,channels:3,background:'#ff0000'}}).png().toFile(solid);
const outImage=async(id,options={},input=image)=>pixels((await run(id,[input],options)).outputs[0]);
check('image-enhance','Expands a low-contrast image, preserves dimensions and changes pixels',async()=>{const out=await outImage('image-enhance');assert.equal(out.info.width,W);assert.equal(out.info.height,H);assert.ok(range(out)>range(source)*1.15);assert.ok(difference(source,out)>3);});
check('image-resize','Fits requested bounds without changing aspect ratio',async()=>{const im=await outImage('image-resize',{width:100,height:100});assert.equal(im.info.width,100);assert.equal(im.info.height,75);});
check('image-crop','Extracts the requested source coordinates exactly',async()=>{const im=await outImage('image-crop',{left:20,top:30,width:70,height:50});assert.equal(im.info.width,70);assert.equal(im.info.height,50);assert.deepEqual(pixel(im,0,0),pixel(source,20,30));assert.deepEqual(pixel(im,69,49),pixel(source,89,79));});
for(const [id,format] of [['image-jpeg','jpeg'],['image-png','png'],['image-webp','webp'],['image-avif','heif']])check(id,'Decodes to the intended format and preserves image content',async()=>{const file=(await run(id,[image],{quality:95})).outputs[0],meta=await sharp(file).metadata();assert.equal(meta.format,format);const im=await pixels(file);assert.equal(im.info.width,W);assert.ok(difference(source,im)<8);});
check('image-rotate','90 degree clockwise pixel mapping',async()=>{const im=await outImage('image-rotate',{angle:90});assert.equal(im.info.width,H);assert.equal(im.info.height,W);assert.deepEqual(pixel(im,H-1-30,20),pixel(source,20,30));});
check('image-flip','Vertical reflection pixel mapping',async()=>assert.deepEqual(pixel(await outImage('image-flip'),20,H-1-30),pixel(source,20,30)));
check('image-mirror','Horizontal reflection pixel mapping',async()=>assert.deepEqual(pixel(await outImage('image-mirror'),W-1-20,30),pixel(source,20,30)));
check('image-grayscale','Every decoded pixel has equal RGB channels',async()=>{const im=await outImage('image-grayscale');for(let i=0;i<im.data.length;i+=4){assert.equal(im.data[i],im.data[i+1]);assert.equal(im.data[i],im.data[i+2]);}});
check('image-blur','Reduces measured edge variation',async()=>assert.ok(edge(await outImage('image-blur',{sigma:5}))<edge(source)*.8));
check('image-sharpen','Increases edge contrast on a soft input',async()=>assert.ok(edge(await outImage('image-sharpen',{sigma:2},blurred))>edge(await pixels(blurred))*1.1));
check('image-brightness','Lightening and darkening change channel means in opposite directions',async()=>{assert.ok(mean((await outImage('image-brightness',{amount:1.4})).data)>mean(source.data));assert.ok(mean((await outImage('image-brightness',{amount:.6})).data)<mean(source.data));});
check('image-saturation','Zero saturation removes chroma',async()=>{const im=await outImage('image-saturation',{amount:0});for(let i=0;i<im.data.length;i+=4)assert.ok(Math.max(...im.data.subarray(i,i+3))-Math.min(...im.data.subarray(i,i+3))<=1);});
check('image-negative','Inverts RGB while preserving alpha',async()=>{const im=await outImage('image-negative');for(const [x,y] of [[0,0],[100,90],[319,239]])assert.deepEqual(pixel(im,x,y),pixel(source,x,y).map((v,i)=>i===3?v:255-v));});
check('image-trim','Removes only the uniform border',async()=>{const im=await outImage('image-trim',{},bordered);assert.equal(im.info.width,W);assert.equal(im.info.height,H);assert.equal(difference(source,im),0);});
check('image-thumbnail','Produces the selected square dimensions',async()=>{const im=await outImage('image-thumbnail',{width:80});assert.equal(im.info.width,80);assert.equal(im.info.height,80);assert.ok(range(im)>30);});
check('image-border','Adds the specified color and preserves inner pixels',async()=>{const im=await outImage('image-border',{width:7,color:'#123456'});assert.equal(im.info.width,W+14);assert.deepEqual(pixel(im,0,0),[18,52,86,255]);assert.deepEqual(pixel(im,27,37),pixel(source,20,30));});
check('image-metadata','Reports real dimensions, codec and EXIF',async()=>{const value=JSON.parse((await run('image-metadata',[tagged])).text);assert.equal(value.width,W);assert.equal(value.height,H);assert.equal(value.format,'jpeg');assert.ok(value.exif);});
check('image-strip','Removes actual embedded EXIF without losing dimensions',async()=>{assert.ok((await sharp(tagged).metadata()).exif);const meta=await sharp((await run('image-strip',[tagged])).outputs[0]).metadata();assert.equal(meta.exif,undefined);assert.equal(meta.width,W);});
check('image-pixelate','Creates constant-color blocks, preserving dimensions',async()=>{const im=await outImage('image-pixelate',{block:16});assert.equal(im.info.width,W);assert.deepEqual(pixel(im,0,0),pixel(im,10,10));assert.notDeepEqual(pixel(im,0,0),pixel(im,30,30));});
check('image-tint','Requested red tint dominates blue/green',async()=>{const p=pixel(await outImage('image-tint',{color:'#ff0000'}),100,100);assert.ok(p[0]>p[1]*2&&p[0]>p[2]*2);});
check('image-threshold','Produces both black and white pixels and no gray',async()=>{const im=await outImage('image-threshold',{threshold:125});const colors=new Set();for(let i=0;i<im.data.length;i+=4){assert.ok(im.data[i]===0||im.data[i]===255);assert.equal(im.data[i],im.data[i+1]);colors.add(im.data[i]);}assert.equal(colors.size,2);});
check('image-rounded','Corners become transparent; center remains opaque',async()=>{const im=await outImage('image-rounded',{radius:40});assert.equal(pixel(im,0,0)[3],0);assert.equal(pixel(im,160,120)[3],255);});
check('image-contact','Places multiple distinct inputs in correct cells',async()=>{const im=await pixels((await run('image-contact',[solid,image],{columns:2,width:80})).outputs[0]);assert.equal(im.info.width,160);assert.equal(im.info.height,80);assert.deepEqual(pixel(im,40,40),[255,0,0,255]);assert.notDeepEqual(pixel(im,120,40),pixel(im,40,40));});
check('image-watermark','Changes the bottom overlay while preserving the top',async()=>{const im=await outImage('image-watermark',{label:'AUDIT',opacity:.5});assert.deepEqual(pixel(im,50,20),pixel(source,50,20));assert.notDeepEqual(pixel(im,50,H-5),pixel(source,50,H-5));});
check('image-palette','Identifies a solid red source as 100 percent red',async()=>{const colors=JSON.parse((await run('image-palette',[solid])).text);assert.equal(colors[0].hex,'#ff0000');assert.equal(colors[0].percent,100);});

const exact=(id,input,expected,options={})=>check(id,'Output matches independently specified expected content',async()=>assert.equal((await run(id,[],options,input)).text,expected));
exact('text-upper','Hello café','HELLO CAFÉ');exact('text-lower','Hello CAFÉ','hello café');exact('text-title',"hello world / élan déjà / don't","Hello World / Élan Déjà / Don't");exact('text-slug',' Crème & Café! ','creme-cafe');exact('text-sort','z\na\nm','a\nm\nz');exact('text-unique','a\nb\na','a\nb');exact('text-trim',' a \n\n b\t','a\nb');
exact('text-json','{"x":2,"ok":true}','{\n  "x": 2,\n  "ok": true\n}');exact('text-json-min','{ "x": 2, "ok": true }','{"x":2,"ok":true}');exact('text-base64','hello','aGVsbG8=');exact('text-unbase64','8J+Zgg==','🙂');exact('text-url','a & b/é','a%20%26%20b%2F%C3%A9');exact('text-unurl','a%20%26%20b%2F%C3%A9','a & b/é');exact('text-sha256','abc','ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');
exact('text-html-escape','<p a="x">&\'</p>','&lt;p a=&quot;x&quot;&gt;&amp;&apos;&lt;/p&gt;');exact('text-html-unescape','&lt;tag&gt;&#x1F642;&#233;','<tag>🙂é');exact('text-number-lines','one\ntwo','1. one\n2. two');exact('text-replace','a.b a.b','ok ok',{find:'a.b',replacement:'ok'});
check('text-stats','Counts Unicode characters, words and lines',async()=>assert.deepEqual(JSON.parse((await run('text-stats',[],{},'Hi 🙂\nWorld')).text),{characters:10,words:3,lines:2,readingMinutes:1}));
check('text-uuid','Requested count, valid v4 UUID bits and no duplicates',async()=>{const ids=(await run('text-uuid',[],{count:80})).text.split('\n');assert.equal(ids.length,80);assert.equal(new Set(ids).size,80);ids.forEach(id=>assert.match(id,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/));});
check('text-password','Requested length and distinct generated samples',async()=>{const values=[];for(let i=0;i<4;i++){const value=(await run('text-password',[],{length:40})).text;assert.equal(value.length,40);values.push(value);}assert.equal(new Set(values).size,4);});
check('text-qr','Independent QR reader decodes the original Unicode payload',async()=>{const payload='Switchyard / audit / café / 123';const im=await pixels((await run('text-qr',[],{},payload)).outputs[0]);assert.equal(jsQR(new Uint8ClampedArray(im.data),im.info.width,im.info.height)?.data,payload);});
check('text-csv-json','Preserves quoted commas, newlines, quotes and Unicode',async()=>assert.deepEqual(JSON.parse((await run('text-csv-json',[],{},'Name,Note\r\n"Café","a,b\nline ""two"""')).text),[{Name:'Café',Note:'a,b\nline "two"'}]));
check('text-json-csv','CSV round trip preserves field values and quoting',async()=>{const rows=[{name:'a,b',note:'"quoted"\nnext',n:4}];assert.deepEqual(parseCsv((await run('text-json-csv',[],{},JSON.stringify(rows))).text),[{name:'a,b',note:'"quoted"\nnext',n:'4'}]);});
check('text-diff','Marks the exact removed and added lines',async()=>{const value=(await run('text-diff',[],{other:'same\nnew\n'},'same\nold\n')).text;assert.match(value,/  same/);assert.match(value,/- old/);assert.match(value,/\+ new/);});
check('text-jwt','Decodes known claims and reports unverified signature',async()=>{const token=Buffer.from('{"alg":"HS256"}').toString('base64url')+'.'+Buffer.from('{"sub":"audit","n":42}').toString('base64url')+'.signature';const value=JSON.parse((await run('text-jwt',[],{},token)).text);assert.deepEqual(value.claims,{sub:'audit',n:42});assert.match(value.warning,/NOT verified/);});
for(const [id,options,key,value] of [['unit-length',{value:1,unit:'miles'},'meters',1609.344],['unit-mass',{value:1,unit:'pounds'},'kilograms',.45359237],['unit-temperature',{value:32,unit:'Fahrenheit'},'Celsius',0],['unit-storage',{value:1,unit:'GiB'},'bytes',1073741824],['date-distance',{from:'2024-02-28',to:'2024-03-01'},'days',2]])check(id,'Returns a known reference conversion',async()=>near(JSON.parse((await run(id,[],options)).text)[key],value,1e-8));
check('number-base','Preserves large integers without floating-point rounding',async()=>{const value=JSON.parse((await run('number-base',[],{value:'FFFFFFFFFFFFFFFF',base:'16'})).text);assert.equal(value.decimal,'18446744073709551615');assert.equal(value.binary,'1'.repeat(64));});
check('color-inspect','Known white and red RGB/HSL/contrast reference values',async()=>{const white=JSON.parse((await run('color-inspect',[],{color:'#ffffff'})).text);near(white.contrastWithBlack,21);near(white.contrastWithWhite,1);const red=JSON.parse((await run('color-inspect',[],{color:'#ff0000'})).text);assert.deepEqual(red.rgb,[255,0,0]);assert.deepEqual(red.hsl,[0,100,50]);});

const pdf=path.join(work,'pages.pdf'),doc=await PDFDocument.create();doc.setTitle('Audit source');doc.setAuthor('Synthetic');for(let i=0;i<3;i++)doc.addPage([300+i*20,400+i*20]).drawText('PAGE '+(i+1)+' - content survives',{x:20,y:200,size:14});await fs.writeFile(pdf,await doc.save());
async function readPdf(file){const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');const task=pdfjs.getDocument({data:new Uint8Array(await fs.readFile(file)),useSystemFonts:true,isEvalSupported:false});const d=await task.promise;try{const texts=[];for(let i=1;i<=d.numPages;i++)texts.push((await (await d.getPage(i)).getTextContent()).items.map(x=>x.str).join(' '));return texts;}finally{await task.destroy();}}
check('pdf-merge','Combines two documents in order with text intact',async()=>{const texts=await readPdf((await run('pdf-merge',[pdf,pdf])).outputs[0]);assert.equal(texts.length,6);assert.match(texts[0],/PAGE 1/);assert.match(texts[3],/PAGE 1/);assert.match(texts[5],/PAGE 3/);});
check('pdf-extract','Extracts exactly the requested pages',async()=>{const texts=await readPdf((await run('pdf-extract',[pdf],{start:2,end:3})).outputs[0]);assert.equal(texts.length,2);assert.match(texts[0],/PAGE 2/);assert.match(texts[1],/PAGE 3/);});
check('pdf-reverse','Reverses readable page content order',async()=>{const texts=await readPdf((await run('pdf-reverse',[pdf])).outputs[0]);assert.match(texts[0],/PAGE 3/);assert.match(texts[2],/PAGE 1/);});
check('pdf-rotate','Rotates every page while preserving content',async()=>{const p=(await run('pdf-rotate',[pdf])).outputs[0];const d=await PDFDocument.load(await fs.readFile(p));d.getPages().forEach(p=>assert.equal(p.getRotation().angle,90));assert.match((await readPdf(p))[1],/PAGE 2/);});
check('pdf-images','Embeds every source image at the correct page dimensions',async()=>{const p=(await run('pdf-images',[image,solid])).outputs[0],d=await PDFDocument.load(await fs.readFile(p));assert.equal(d.getPageCount(),2);assert.equal(d.getPage(0).getWidth(),W);assert.equal(d.getPage(1).getWidth(),80);const render=await run('pdf-render',[p],{scale:1});assert.ok(difference(source,await pixels(render.outputs[0]))<1);});
check('pdf-metadata','Reads actual title, author and page count',async()=>{const value=JSON.parse((await run('pdf-metadata',[pdf])).text);assert.equal(value.title,'Audit source');assert.equal(value.author,'Synthetic');assert.equal(value.pages,3);});
check('pdf-split','Creates one readable PDF per original page',async()=>{const r=await run('pdf-split',[pdf]);assert.equal(r.outputs.length,3);for(let i=0;i<3;i++){const texts=await readPdf(r.outputs[i]);assert.equal(texts.length,1);assert.match(texts[0],new RegExp('PAGE '+(i+1)));}});
check('pdf-delete','Removes only the selected page',async()=>{const texts=await readPdf((await run('pdf-delete',[pdf],{start:2,end:2})).outputs[0]);assert.equal(texts.length,2);assert.match(texts[0],/PAGE 1/);assert.match(texts[1],/PAGE 3/);});
check('pdf-number','Adds the correct number to each page and preserves source text',async()=>{const texts=await readPdf((await run('pdf-number',[pdf])).outputs[0]);texts.forEach((t,i)=>{assert.match(t,/content survives/);assert.match(t,new RegExp(' '+(i+1)+'$'));});});
check('pdf-watermark','Watermark text appears on every page',async()=>{const texts=await readPdf((await run('pdf-watermark',[pdf],{label:'AUDIT STAMP'})).outputs[0]);texts.forEach(t=>assert.match(t,/AUDIT STAMP/));});
check('pdf-text','Extracts actual embedded content from every page',async()=>{const text=(await run('pdf-text',[pdf])).text;for(let i=1;i<=3;i++)assert.match(text,new RegExp('PAGE '+i));});
check('pdf-render','Renders all pages with scaled dimensions and visible text pixels',async()=>{const r=await run('pdf-render',[pdf],{scale:1.5});assert.equal(r.outputs.length,3);for(let i=0;i<3;i++){const im=await pixels(r.outputs[i]);assert.equal(im.info.width,(300+i*20)*1.5);assert.ok(im.data.some((v,j)=>j%4!==3&&v<100));}});
check('pdf-edit-info','Saves requested metadata without losing page content',async()=>{const p=(await run('pdf-edit-info',[pdf],{title:'New title',author:'New author'})).outputs[0],d=await PDFDocument.load(await fs.readFile(p));assert.equal(d.getTitle(),'New title');assert.equal(d.getAuthor(),'New author');assert.match((await readPdf(p))[2],/PAGE 3/);});
check('text-pdf','Long text paginates and preserves its final paragraph',async()=>{const text=Array.from({length:110},(_,i)=>'Line '+i+' content').join('\n');const pages=await readPdf((await run('text-pdf',[],{},text)).outputs[0]);assert.ok(pages.length>=3);assert.match(pages.join('\n'),/Line 109 content/);});

// Audio fixtures include silence, a quiet section, low/high tones and a varying envelope.
const rate=48000,duration=4,samples=rate*duration,audio=path.join(work,'signal.wav'),pcm=Buffer.alloc(samples*2*2);
for(let n=0;n<samples;n++){const t=n/rate,amp=t<.4?0:t<2?.12:.24;const left=amp*(Math.sin(2*Math.PI*220*t)+.4*Math.sin(2*Math.PI*6000*t));const right=amp*.5*Math.sin(2*Math.PI*440*t);pcm.writeInt16LE(Math.round(left*32767),n*4);pcm.writeInt16LE(Math.round(right*32767),n*4+2);}
const rawPath=path.join(work,'signal.pcm');await fs.writeFile(rawPath,pcm);await command(engines.ffmpeg,['-v','error','-f','s16le','-ar',String(rate),'-ac','2','-i',rawPath,audio]);
const probe=async file=>JSON.parse(await command(engines.ffprobe,['-v','error','-show_streams','-show_format','-of','json',file]));
async function decode(file){const p=path.join(work,'decoded-'+(++serial)+'.f32');await command(engines.ffmpeg,['-v','error','-i',file,'-map','0:a:0','-ac','1','-ar',String(rate),'-f','f32le',p]);const b=await fs.readFile(p);return new Float32Array(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));}
const rms=(a,start,end)=>{const s=Math.round(start*rate),e=Math.min(a.length,Math.round(end*rate));let sum=0;for(let i=s;i<e;i++)sum+=a[i]*a[i];return Math.sqrt(sum/(e-s));};
const tone=(a,hz)=>{let c=0,s=0;for(let i=rate;i<rate*2&&i<a.length;i++){c+=a[i]*Math.cos(2*Math.PI*hz*i/rate);s+=a[i]*Math.sin(2*Math.PI*hz*i/rate);}return Math.hypot(c,s);};
const baseline=await decode(audio);
for(const [id,codec] of [['audio-wav','pcm_s16le'],['audio-mp3','mp3'],['audio-flac','flac'],['audio-aac','aac'],['audio-opus','opus']])check(id,'Actual audio codec, duration and audible waveform survive conversion',async()=>{const file=(await run(id,[audio])).outputs[0],p=await probe(file),a=await decode(file);assert.equal(p.streams[0].codec_name,codec);near(Number(p.format.duration),4,.15);assert.ok(rms(a,1,2)>.03);assert.ok(tone(a,220)>tone(a,300)*20);});
check('audio-trim','Requested nonzero start and duration select the correct envelope',async()=>{const a=await decode((await run('audio-trim',[audio],{start:2.5,duration:1})).outputs[0]);near(a.length/rate,1,.01);near(rms(a,.1,.8),rms(baseline,2.6,3.3),.003);});
check('audio-normalize','Measured integrated loudness reaches the advertised target',async()=>{const file=(await run('audio-normalize',[audio])).outputs[0];let log='';await command(engines.ffmpeg,['-hide_banner','-i',file,'-af','loudnorm=I=-16:TP=-1.5:LRA=11:print_format=json','-f','null','-'],{onLog:t=>log+=t});const match=log.match(/\{\s*"input_i"[\s\S]*?\}/);assert.ok(match);near(Number(JSON.parse(match[0]).input_i),-16,1);});
check('audio-volume','Gain changes decoded RMS by the specified decibels',async()=>{const a=await decode((await run('audio-volume',[audio],{gain:-6})).outputs[0]);near(20*Math.log10(rms(a,1,2)/rms(baseline,1,2)),-6,.05);});
check('audio-fade-in','Beginning attenuates while the later section stays unchanged',async()=>{const a=await decode((await run('audio-fade-in',[audio],{duration:2})).outputs[0]);assert.ok(rms(a,.5,.7)<rms(baseline,.5,.7)*.4);near(rms(a,3,3.5),rms(baseline,3,3.5),.001);});
check('audio-fade-out','End attenuates while the beginning stays unchanged',async()=>{const a=await decode((await run('audio-fade-out',[audio],{duration:2})).outputs[0]);assert.ok(rms(a,3.5,3.8)<rms(baseline,3.5,3.8)*.3);near(rms(a,1,1.5),rms(baseline,1,1.5),.001);});
check('audio-reverse','Decoded samples appear in reverse temporal order',async()=>{const a=await decode((await run('audio-reverse',[audio])).outputs[0]);assert.equal(a.length,baseline.length);let error=0;for(let i=0;i<a.length;i++)error+=Math.abs(a[i]-baseline[a.length-1-i]);assert.ok(error/a.length<.0001);});
check('audio-speed','Double speed halves duration while preserving pitch',async()=>{const a=await decode((await run('audio-speed',[audio],{speed:2})).outputs[0]);near(a.length/rate,2,.08);assert.ok(tone(a,220)>tone(a,300)*10);});
check('audio-mono','Creates one channel with the mixed source signal',async()=>{const file=(await run('audio-mono',[audio])).outputs[0];assert.equal((await probe(file)).streams[0].channels,1);near(rms(await decode(file),1,2),rms(baseline,1,2)/Math.sqrt(2),.001);});
check('audio-denoise','Preserves the dominant tone and attenuates quiet noise',async()=>{const noise=path.join(work,'noise.wav');await command(engines.ffmpeg,['-v','error','-f','lavfi','-i','anoisesrc=color=white:amplitude=0.006:duration=4:seed=42','-ar',String(rate),noise]);const before=await decode(noise),after=await decode((await run('audio-denoise',[noise])).outputs[0]);assert.ok(rms(after,2,3)<rms(before,2,3)*.9);const musical=await decode((await run('audio-denoise',[audio])).outputs[0]);assert.ok(tone(musical,220)>tone(baseline,220)*.5);});
check('audio-highpass','Attenuates low frequencies more than high frequencies',async()=>{const a=await decode((await run('audio-highpass',[audio],{frequency:1000})).outputs[0]);assert.ok(tone(a,220)/tone(baseline,220)<.15);assert.ok(tone(a,6000)/tone(baseline,6000)>.8);});
check('audio-lowpass','Attenuates high frequencies while retaining low frequencies',async()=>{const a=await decode((await run('audio-lowpass',[audio],{frequency:1000})).outputs[0]);assert.ok(tone(a,6000)/tone(baseline,6000)<.08);assert.ok(tone(a,220)/tone(baseline,220)>.8);});
check('audio-silence','Removes leading silence and keeps audible material',async()=>{const a=await decode((await run('audio-silence',[audio])).outputs[0]);near(a.length/rate,3.6,.05);assert.ok(rms(a,0,.1)>.01);});
check('audio-inspect','Reports source channel count, sample rate and duration',async()=>{const p=JSON.parse((await run('audio-inspect',[audio])).text);assert.equal(p.streams[0].channels,2);assert.equal(Number(p.streams[0].sample_rate),rate);near(Number(p.format.duration),4);});
const video=path.join(work,'video.mp4');await command(engines.ffmpeg,['-v','error','-loop','1','-i',image,'-i',audio,'-t','4','-r','12','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac',video]);
for(const [id,options] of [['video-mp4',{}],['video-webm',{}],['video-compress',{crf:35}],['video-resize',{width:160}],['video-trim',{start:1,duration:1}],['video-speed',{speed:2}],['video-mute',{}]])check(id,'Decodes video frames with correct codec, dimensions, duration and stream selection',async()=>{const file=(await run(id,[video],options)).outputs[0],p=await probe(file),v=p.streams.find(s=>s.codec_type==='video');assert.ok(v);assert.equal(v.width,id==='video-resize'?160:W);near(Number(p.format.duration),id==='video-trim'?1:id==='video-speed'?2:4,.22);assert.equal(p.streams.some(s=>s.codec_type==='audio'),id!=='video-mute');assert.equal(v.codec_name,id==='video-webm'?'vp9':'h264');const frame=path.join(work,'frame-'+(++serial)+'.png');await command(engines.ffmpeg,['-v','error','-i',file,'-frames:v','1',frame]);assert.ok(range(await pixels(frame))>30);});
check('video-extract','Extracted audio retains pitch and duration without video',async()=>{const file=(await run('video-extract',[video])).outputs[0],p=await probe(file);assert.equal(p.streams.length,1);assert.equal(p.streams[0].codec_type,'audio');near(Number(p.format.duration),4,.1);assert.ok(tone(await decode(file),220)>1);});
check('video-gif','Animated GIF has multiple decoded frames and expected duration',async()=>{const file=(await run('video-gif',[video],{start:1,duration:1})).outputs[0],meta=await sharp(file,{animated:true}).metadata();assert.equal(meta.format,'gif');assert.ok(meta.pages>=10);assert.equal(meta.width,480);});
check('video-frame','Extracted PNG contains the source frame at original dimensions',async()=>{const im=await pixels((await run('video-frame',[video],{start:1})).outputs[0]);assert.equal(im.info.width,W);assert.ok(difference(source,im)<8);});
check('video-rotate','Clockwise rotation maps asymmetric source pixels correctly',async()=>{const file=(await run('video-rotate',[video])).outputs[0],p=await probe(file);assert.equal(p.streams[0].width,H);assert.equal(p.streams[0].height,W);const frame=path.join(work,'rotated.png');await command(engines.ffmpeg,['-v','error','-i',file,'-frames:v','1',frame]);const im=await pixels(frame);pixel(im,H-1-30,20).forEach((v,i)=>near(v,pixel(source,20,30)[i],8));});
check('video-mirror','Horizontally mirrors decoded frame coordinates',async()=>{const file=(await run('video-mirror',[video])).outputs[0],frame=path.join(work,'mirrored.png');await command(engines.ffmpeg,['-v','error','-i',file,'-frames:v','1',frame]);const im=await pixels(frame);pixel(im,W-1-20,30).forEach((v,i)=>near(v,pixel(source,20,30)[i],8));});
const ocrImage=path.join(work,'ocr.png');await sharp(Buffer.from('<svg width="1000" height="200"><rect width="100%" height="100%" fill="white"/><text x="20" y="120" font-size="60" fill="black">AUDIT 7429 LOCAL TEXT</text></svg>')).png().toFile(ocrImage);
check('image-ocr','Recognizes a known sentence and digits from image pixels',async()=>assert.match((await run('image-ocr',[ocrImage])).text,/AUDIT 7429 LOCAL TEXT/));

try{
 for(const c of cases){if(process.env.ONLY_OUTCOMES&&!new RegExp(process.env.ONLY_OUTCOMES).test(c.id))continue;const start=performance.now();try{await c.fn();results.push({tool:c.id,pass:true,assertion:c.description,ms:Math.round(performance.now()-start)});console.log('PASS '+c.id+' — '+c.description);}catch(e){results.push({tool:c.id,pass:false,assertion:c.description,error:e.stack,ms:Math.round(performance.now()-start)});console.log('FAIL '+c.id+' — '+e.message);}}
 const audited=new Set(results.map(r=>r.tool)),pending=tools.filter(t=>!audited.has(t.id)).map(t=>t.id);const report={passed:results.filter(r=>r.pass).length,failed:results.filter(r=>!r.pass).length,executor:process.env.SWITCHYARD_TEST_EXE||'source processor',results,pending,work};await fs.writeFile(path.join(root,'docs/verification/outcome-audit'+(process.env.ONLY_OUTCOMES?'-subset':'')+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,failed:report.failed,pending}));if(report.failed)process.exitCode=1;
}finally{await app?.close();}
