import {_electron} from 'playwright';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import sharp from 'sharp';
const root=path.resolve('.'),work=path.join(root,'.runtime-workshop-'+Date.now());await fs.mkdir(work,{recursive:true});
const photo=path.join(work,'small.png'),unknown=path.join(work,'unknown.zzz');await sharp({create:{width:80,height:60,channels:3,background:'#338855'}}).png().toFile(photo);await fs.writeFile(unknown,'Unsupported file');
const env={...process.env,SWITCHYARD_TEST_DATA:path.join(work,'profile')};delete env.ELECTRON_RUN_AS_NODE;
const app=await _electron.launch({executablePath:process.env.SWITCHYARD_TEST_EXE||path.join(root,'node_modules/electron/dist/electron.exe'),args:process.env.SWITCHYARD_TEST_EXE?[]:[root],env});const results=[];
const pick=files=>app.evaluate(({dialog},files)=>{dialog.showOpenDialog=async()=>({canceled:!files.length,filePaths:files});},files);
try{
 const page=await app.firstWindow();page.setDefaultTimeout(20000);
 await page.getByRole('button',{name:/^Batch converter/}).click();assert.ok(await page.getByRole('button',{name:/Drop in your next batch/}).count());await pick([photo,unknown]);await page.getByRole('button',{name:/Drop in your next batch/}).click();await page.getByRole('combobox',{name:'Apply format to compatible files'}).selectOption('webp');assert.equal(await page.getByRole('combobox',{name:'Output format for small.png'}).inputValue(),'webp');results.push('empty batch picker, mixed files and compatible target selection');
 await page.getByRole('button',{name:'Convert 1 files'}).click();await page.waitForFunction(()=>document.querySelector('.job-top p')?.textContent.includes('partial'));const state=await page.evaluate(()=>window.switchyard.state());assert.equal(state.jobs[0].status,'partial');assert.equal(state.jobs[0].outputs.length,2);assert.equal((await sharp(state.jobs[0].outputs.find(p=>p.endsWith('.webp'))).metadata()).width,80);results.push('mixed batch succeeds for supported files and reports unsupported file');
 await page.getByRole('button',{name:'Use results in another tool'}).first().click();await page.waitForFunction(()=>document.querySelectorAll('.tray-file').length>=3);results.push('reuse result files');
 const exported=path.join(work,'saved.webp');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},exported);await page.getByRole('button',{name:'Save first output as'}).first().click();await page.waitForTimeout(150);assert.ok((await fs.stat(exported)).size>0);results.push('save output');
 await page.getByRole('button',{name:'Clear tray',exact:true}).click();await pick([photo]);await page.getByRole('button',{name:'Add files',exact:true}).first().click();await page.getByRole('textbox',{name:'Search tools'}).fill('Crop image');await page.locator('.tool-open').filter({has:page.getByRole('heading',{name:'Crop image',exact:true})}).click();await page.locator('.crop-image').waitFor();const dialog=page.getByRole('dialog');const width=dialog.getByRole('spinbutton',{name:/Width/});assert.ok(Number(await width.inputValue())<=80);for(const name of ['Square','16:9','4:3']){await dialog.getByRole('button',{name,exact:true}).click();assert.ok(Number(await width.inputValue())<=80);}results.push('small-image crop defaults and three crop presets');
 const rect=await page.locator('.crop-image').boundingBox();await page.mouse.move(rect.x+rect.width*.1,rect.y+rect.height*.1);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.6,rect.y+rect.height*.6);await page.mouse.up();await page.getByRole('button',{name:'Run tool'}).click();await page.waitForFunction(()=>document.querySelector('.job-top p')?.textContent.includes('done'));const cropped=(await page.evaluate(()=>window.switchyard.state())).jobs[0].outputs[0];const info=await sharp(cropped).metadata();assert.ok(info.width<80&&info.height<60);results.push('drag crop selection produces correct smaller image');
 await fs.writeFile(path.join(root,'docs/verification/workshop-flows.json'),JSON.stringify({passed:results.length,results},null,2));console.log(results);
}finally{await app.close();}
